sudo: required
dist: trusty
services:
 - docker
addons:
  apt:
    packages:
    - linux-generic
    - linux-image-$(uname -r)
    - linux-headers-$(uname -r)
install:
 - curl -L http://download.virtualbox.org/virtualbox/5.0.26/virtualbox-5.0_5.0.26-108824~Ubuntu~trusty_amd64.deb -o virtualbox-5.0_5.0.26.deb && sudo dpkg -i virtualbox-5.0_5.0.26.deb
 - curl -L http://download.virtualbox.org/virtualbox/5.0.26/Oracle_VM_VirtualBox_Extension_Pack-5.0.26-108824.vbox-extpack -o Oracle_VM_VirtualBox_Extension_Pack-5.0.26-108824.vbox-extpack && sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.0.26-108824.vbox-extpack
 - curl -L https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb -o vagrant_1.8.1_x86_64.deb && sudo dpkg -i vagrant_1.8.1_x86_64.deb
