FROM ubuntu:14.04
# Install Ansible
RUN apt-get update && apt-get install -y \
    software-properties-common \
    git \
    && apt-add-repository -y ppa:ansible/ansible \
    && apt-get install -y ansible \
# Install Ansible inventory file
    && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
COPY requirements.yml /etc/ansible/requirements.yml
COPY test.yml /etc/ansible/test.yml
#RUN ansible-galaxy install -r /etc/ansible/requirements.yml
